import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
import test from "node:test";

const runtime = fs.readFileSync(new URL("../src/translation-loader/js/figmaCN.js", import.meta.url), "utf8");
const dictionary = JSON.parse(fs.readFileSync(new URL("../src/translation-loader/js/lang.cn.json", import.meta.url)));
const menuDictionary = JSON.parse(fs.readFileSync(new URL("../src/translation-loader/js/lang.cn.menu.json", import.meta.url)));
const fixtures = {
"You now have a Full seat in {planName} — you have full access to Figma Design, Figma Sites, Dev Mode, FigJam, and Figma Slides. ": "您现在拥有 {planName} 中的完整席位，可完整访问 Figma Design、Figma Sites、Dev Mode、FigJam 和 Figma Slides。 ",
"If you’re receiving this message in error, {supportLink}.": "如果您误收到此消息，请查看 {supportLink}。",
"Prepaid credits expire {date}": "预付点数将于 {date} 到期",
"Total {seatType} seats": "{seatType} 席位总数",
"Approve request for {name}": "批准 {name} 的请求",
"Request details for {name}": "{name} 的请求详情",
"Reminder sent {time}": "提醒已于 {time} 发送",
"App access requested by {name}": "{name} 请求访问应用",
"Request from {requesterName} approved": "已批准 {requesterName} 的请求",
"All requests in {planName}": "{planName} 中的所有请求",
"Welcome to {planName} admin": "欢迎使用 {planName} 管理后台",
"Manage paid credits for {userName}": "管理 {userName} 的付费点数",
"No results found for {searchQuery}": "未找到与 {searchQuery} 匹配的结果",
"Cloned {repoName}": "已克隆 {repoName}",
"Cloning {repoName}": "正在克隆 {repoName}",
"Uploaded {folderName}": "已上传 {folderName}",
"Uploading {folderName}": "正在上传 {folderName}",
"Importing {repoName}": "正在导入 {repoName}",
"Seat type: {seatType}": "席位类型：{seatType}",
"Monthly reset: {resetsAt}": "每月重置：{resetsAt}",
"Slide {number}": "幻灯片 {number}",
"Agent - {name}": "智能体 - {name}",
"{seatType} seats": "{seatType} 席位",
"You can view and manage all of the seat requests from people in {planName}.": "您可以查看和管理 {planName} 中人员的所有席位请求。",
"Approving adds one paid {seatType} seat.": "批准后将新增一个付费 {seatType} 席位。",
"This will use one available {seatType} seat.": "这将使用一个可用的 {seatType} 席位。",
"{user}'s request": "{user} 的请求",
"Approving adds 1 {seatType} seat.": "批准后将新增 1 个 {seatType} 席位。",
"A teammate requested a {seatType} for another teammate": "一位队友为另一位队友申请了 {seatType} 席位",
"{requesterName} sent you a reminder": "{requesterName} 向你发送了提醒",
"Last requested {time}": "上次请求于 {time}",
"{planName} admin": "{planName} 管理后台",
"{monthlyCredits} paid credits used": "已使用 {monthlyCredits} 点付费点数",
"{paygBudget} pay as you go budget": "按量付费预算：{paygBudget}",
"{prepaidCredits} Prepaid credits": "{prepaidCredits} 预付点数",
"{prepaidCredits} used": "已使用 {prepaidCredits}",
"{user} was auto-approved when they created a file.": "用户 {user} 创建文件时已自动批准",
"{user} was auto-approved when they used Dev Mode in a file.": "用户 {user} 在文件中使用 Dev Mode 时已自动批准",
"{user} was auto-approved when they shared a file from their drafts.": "用户 {user} 从草稿中共享文件时已自动批准",
"{user} was auto-approved when they began editing a file.": "用户 {user} 开始编辑文件时已自动批准",
"{user} was upgraded.": "{user} 已升级。",
"Choose how many paid AI credits {user} can use each month.": "选择 {user} 每月可使用的付费 AI 点数。",
"Unless one is available, a new {seatName} seat will be added to your team and shown on your next invoice.": "如果没有可用席位，系统将在下一张发票中为您的团队新增一个 {seatName} 席位。",
"Unless one is available, a new {seatName} seat will be added to your team and prorated on your next invoice.": "如果没有可用席位，系统将在下一张发票中按比例计费新增的 {seatName} 席位。",
"Request approved. {requesterName} moved to a Collab seat.": "请求已批准。{requesterName} 已转为协作席位。",
"Request approved. {requesterName} moved to a Content seat.": "请求已批准。{requesterName} 已转为内容席位。",
"Request approved. {requesterName} moved to a Dev seat.": "请求已批准。{requesterName} 已转为开发席位。",
"Request approved. {requesterName} moved to a Full seat.": "请求已批准。{requesterName} 已转为完整席位。",
"{billableProductKey} seat": "{billableProductKey} 席位",
"Amount of paid credits shared by members of {poolName}.": "由 {poolName} 成员共享的付费点数。",
"Remove {chip} from search": "从搜索中移除 {chip}",
"You have no access to AI credits in {planName}.": "您无权使用 {planName} 中的 AI 点数。",
"We've let your admins know that your billing group in {planName} is out of credits.": "我们已通知 {planName} 的管理员，其账单组已无点数。",
"We’ve let your admins know that {planName} is out of credits.": "我们已通知 {planName} 的管理员，其已无点数。",
"We’ve sent your request for more to {planName} admins.": "我们已将您的更多点数申请发送给 {planName} 管理员。",
"Your access to your billing group’s shared credits is limited to {numCredits} credits.": "您对账单组共享点数的使用权限仅限于 {numCredits} 点。",
"Was added to the {planName} plan before this information was tracked": "在此信息被记录之前已加入 {planName} 计划",
"Became the owner after creating the {planName} plan": "创建 {planName} 计划后成为所有者",
"Was automatically added to the {planName} plan via domain capture": "通过域名自动收纳自动加入 {planName} 计划",
"Automatically added to the {planName} plan when the organization moved to Figma for Government": "组织迁移到 Figma for Government 时自动加入 {planName} 计划",
"Was added to the {planName} plan by Figma Support": "由 Figma 支持添加到 {planName} 计划",
"Joined the {planName} plan when they clicked a join link": "点击加入链接后加入 {planName} 计划",
"Joined the {planName} plan when it was created": "在创建 {planName} 计划时加入",
"Was added to the {planName} plan after requesting to join": "申请加入后添加到 {planName} 计划",
"Joined the {planName} plan when signing in with SSO": "使用 SSO 登录时加入 {planName} 计划",
"Was added to the {planName} plan": "已添加到 {planName} 计划",
"{user} was auto-approved when they ran a plugin.": "用户 {user} 运行插件时已自动批准",
"{user} was auto-approved when they moved their draft file into a shared project.": "用户 {user} 将草稿文件移入共享项目时已通过自动审批",
"{user} was auto-approved when they moved their draft file into a shared folder.": "用户 {user} 将草稿文件移入共享文件夹时已通过自动审批",
"{user} was auto-approved when they published a site.": "用户 {user} 发布网站时已自动批准",
"{user} was auto-approved via an available seat when they ran a plugin.": "用户 {user} 运行插件时已通过可用席位自动批准",
"{user} was auto-approved via an available seat when they published a site.": "用户 {user} 发布网站时已通过可用席位自动批准",
"{user} was auto-approved via an available seat when they created a file.": "用户 {user} 创建文件时已通过可用席位自动批准",
"{user} was auto-approved via an available seat when they used Dev Mode in a file.": "用户 {user} 在文件中使用 Dev Mode 时已通过可用席位自动批准",
"{user} was auto-approved via an available seat when they shared a file from their drafts.": "用户 {user} 从草稿中共享文件时已通过可用席位自动批准",
"{user} was auto-approved via an available seat when they started editing a file.": "用户 {user} 开始编辑文件时已通过可用席位自动批准",
"{user} was auto-approved via an available seat when they moved their draft file into a shared project.": "用户 {user} 将草稿文件移入共享项目时已通过可用席位自动批准",
"{user} was auto-approved via an available seat when they moved their draft file into a shared folder.": "用户 {user} 将草稿文件移入共享文件夹时已通过可用席位自动批准",
"{user} was assigned the Full seat when they joined the organization.": "用户 {user} 加入组织时被分配了完整席位",
"{user} was assigned the Full seat when they joined the team.": "用户 {user} 加入团队时被分配了完整席位",
"This limit is higher than the total amount of paid credits in {poolName}. They’ll only be able to use what is available.": "此上限高于 {poolName} 中的付费点数总量。用户只能使用现有点数。",
"This limit is higher than the total amount of paid credits in {poolName} for this billing group. They’ll only be able to use what is available.": "此上限高于此账单组在 {poolName} 中的付费点数总量。用户只能使用现有点数。",
"Figma file \"{name}\" is attached": "已附加 Figma 文件“{name}”",
"AI model, {model}": "AI 模型：{model}",
"Welcome, {firstName}! Here are a few ways the Figma agent can help you work:": "欢迎，{firstName}！下面是 Figma 智能体可以帮助你完成的一些工作：",
"Budget recently updated to {monetaryValue}/mo": "预算最近更新为每月 {monetaryValue}",
"We sent a confirmation email to {email}!": "确认邮件已发送至 {email}！",
"{planName} received additional credits.": "{planName} 已获得额外点数。",
"Heads up: You’re running {low} on AI credits.": "注意：您的 AI 点数还剩 {low}。",
"You’re running {low} on AI credits.": "您的 AI 点数还剩 {low}。",
"You’re out of daily AI credits for your {seatType} seat.": "您的 {seatType} 席位已用完每日 AI 点数。",
"You’re out of daily AI credits in {planName}. Upgrade your plan to keep prompting today.": "您已用完 {planName} 中的每日 AI 点数。升级计划以继续今天的提示。",
"If you want to keep using AI credits, send a request to an admin at {planName}.": "如果您想继续使用 AI 点数，请向 {planName} 的管理员发送请求。",
"{poolName} is low on credits and doesn’t have enough to cover this user’s limit.": "{poolName} 的点数不足，无法满足此用户的上限。",
"Your access to your billing group’s shared credits is limited to {numCredits} credits a month.": "您对账单组共享点数的使用权限仅限于每月 {numCredits} 点。",
"{planName} is out of credits.": "{planName} 已无点数。",
"{planName} is out of credits. We’ve let your admins know.": "{planName} 已无点数。我们已通知管理员。",
"Split monthly AI credits between billing groups. The rest of {orgName} can use any credits left over.": "在账单组之间分配每月 AI 点数。{orgName} 的其他成员可以使用剩余点数。",
"We sent an email to {email} with instructions to reset your password!": "我们已向 {email} 发送密码重置说明邮件！",
"We sent a verification email to {email}. Please check it to verify your new email.": "我们已向 {email} 发送验证邮件。请查收邮件以验证新邮箱。",
"This transfer can’t be accepted because {sourceName} doesn’t have nested folders enabled.": "由于 {sourceName} 未启用嵌套文件夹，无法接受此转移。",
"{assetName} verified": "{assetName} 已验证",
"This email isn't associated with the {destinationType} linked above. Please confirm that you have the right email.": "此邮箱与上方关联的 {destinationType} 不匹配。请确认使用了正确的邮箱。",
"No results for \"{query}\"": "没有找到“{query}”的结果",
"Clear {tagType} tag": "清除 {tagType} 标签",
"Search across {orgText}": "搜索 {orgText}",
"Choose an account to join {destination}": "选择要加入 {destination} 的账户",
"Choose an account to open {destination}": "选择要打开 {destination} 的账户",
"Choose account to add to the Figma {appDescriptor} app": "选择要添加到 Figma {appDescriptor} 应用的账户",
"Continue with {appDescriptor} app": "继续使用 {appDescriptor} 应用",
"Create an account to collaborate on {displayName}": "创建账户以参与 {displayName} 协作",
"Did you mean {domainSuggestion}?": "你是不是要找 {domainSuggestion}？",
"Please assign a new admin for {currentOrgName} before changing your email domain.": "更改邮箱域名前，请先为 {currentOrgName} 指定新的管理员。",
"User {EMAIL} cannot join the org - they are deprovisioned": "用户 {EMAIL} 无法加入组织，因为该用户已取消配置",
"Please downgrade yourself to a member in {currentOrgName} before changing your email domain.": "更改邮箱域名前，请先将自己降级为 {currentOrgName} 的成员。",
"User {EMAIL} is blocked from joining the org": "用户 {EMAIL} 被禁止加入组织",
"Invalid authentication method: {METHOD}": "身份验证方法无效：{METHOD}",
"Join links have been disabled for {TEAM_NAME}": "已禁用 {TEAM_NAME} 的加入链接",
"Only view-level links are enabled for {TEAM_NAME}": "仅为 {TEAM_NAME} 启用查看级别链接",
"Log in as {email}": "以 {email} 身份登录",
"Log in to collaborate on {displayName}": "登录以参与 {displayName} 协作",
"Authenticated as {email}": "已通过身份验证：{email}",
"Cancel and do not join {orgName}": "取消，不加入 {orgName}",
"Connected cell phone number: {phoneNumber}": "连接的手机号码：{phoneNumber}",
"Open the {appDescriptor} app": "打开 {appDescriptor} 应用",
"{title} is updating.": "{title} 正在更新。",
"{label}, hide agent work details": "{label}，隐藏智能体工作详情",
"{label}, show agent work details": "{label}，显示智能体工作详情",
"Go to selection on canvas: {label}": "转到画布上的选区：{label}",
"+{count} more": "另有 {count} 个",
"Libraries, {count} selected": "组件库，已选择 {count} 个",
"{command}, skill": "{command}，技能",
"Admins at {entity}": "{entity} 的管理员",
"{percent}% there…": "已完成 {percent}%…",
"Create {numVariations} visual variations of this frame that keep the same structure but refresh imagery and styling.": "创建 {numVariations} 个此画框的视觉变体，在保持结构不变的同时更新图像和样式。",
"Additional instructions: {text}": "其他说明：{text}",
"Keep the {keptContentTypes}.": "保留{keptContentTypes}。",
"Replace the {replacedContentTypes}.": "替换{replacedContentTypes}。",
"Number of variations: {numVariations}": "变体数量：{numVariations}",
"Change the {changedAspects}.": "更改{changedAspects}。",
"Create {numVariations} variations of this design.": "创建此设计的 {numVariations} 个变体。",
"Keep the {keptAspects}.": "保留{keptAspects}。",
"A Full seat in {planName} includes higher MCP tool call limits and full access to Figma Make, Figma Design, Figma Sites, Dev Mode, FigJam, and Figma Slides": "{planName} 中的完整席位包含更高的 MCP 工具调用上限，并可完整使用 Figma Make、Figma Design、Figma Sites、Dev Mode、FigJam 和 Figma Slides",
"You’ve been invited to edit this Figma Make file. This will update your seat in {planName}—you’ll get full access to Figma Make, Figma Design, Figma Sites, Dev Mode, FigJam, and Figma Slides.": "您已受邀编辑此 Figma Make 文件。这将更新您在 {planName} 中的席位—您将可以完整使用 Figma Make、Figma Design、Figma Sites、Dev Mode、FigJam 和 Figma Slides。",
"This will update your seat in {planName}—you’ll get full access to Figma Sites, Figma Design, Dev Mode, FigJam, and Figma Slides.": "这将更新您在 {planName} 中的席位—您将可以完整使用 Figma Sites、Figma Design、Dev Mode、FigJam 和 Figma Slides。",
"A Full seat in {planName} includes higher AI credit limits and full access to Figma Sites, Figma Design, Dev Mode, FigJam, and Figma Slides.": "{planName} 中的完整席位包含更高的 AI 点数上限，并可完整使用 Figma Sites、Figma Design、Dev Mode、FigJam 和 Figma Slides。",
"A Full seat in {planName} includes higher MCP tool call limits and full access to Figma Sites, Figma Design, Dev Mode, FigJam, and Figma Slides.": "{planName} 中的完整席位包含更高的 MCP 工具调用上限，并可完整使用 Figma Sites、Figma Design、Dev Mode、FigJam 和 Figma Slides。",
"You’ve been invited to edit this Figma Sites file. This will update your seat in {planName}—you’ll get full access to Figma Sites, Figma Design, Dev Mode, FigJam, and Figma Slides.": "您已受邀编辑此 Figma Sites 文件。这将更新您在 {planName} 中的席位—您将可以完整使用 Figma Sites、Figma Design、Dev Mode、FigJam 和 Figma Slides。",
"This will update your seat in {planName}—you’ll get full access to Figma Slides and FigJam.": "这将更新您在 {planName} 中的席位—您将可以完整使用 Figma Slides 和 FigJam。",
"A Collab seat in {planName} includes higher AI credit limits and full access to Figma Slides and FigJam.": "{planName} 中的协作席位包含更高的 AI 点数上限，并可完整使用 Figma Slides 和 FigJam。",
"You’ve been invited to edit this Figma Slides file. This will update your seat in {planName}—you’ll get full access to Figma Slides and FigJam.": "您已受邀编辑此 Figma Slides 文件。这将更新您在 {planName} 中的席位—您将可以完整使用 Figma Slides 和 FigJam。",
"This will update your seat in {planName}—you’ll get full access to Figma Weave, Figma Make, Figma Design, Figma Sites, Dev Mode, FigJam, and Figma Slides.": "这将更新您在 {planName} 中的席位—您将可以完整使用 Figma Weave、Figma Make、Figma Design、Figma Sites、Dev Mode、FigJam 和 Figma Slides。",
"A Full seat in {planName} includes higher AI credit limits and full access to Figma Weave, Figma Make, Figma Design, Figma Sites, Dev Mode, FigJam, and Figma Slides.": "{planName} 中的完整席位包含更高的 AI 点数上限，并可完整使用 Figma Weave、Figma Make、Figma Design、Figma Sites、Dev Mode、FigJam 和 Figma Slides。",
"A Full seat in {planName} includes higher MCP tool call limits and full access to Figma Weave, Figma Make, Figma Design, Figma Sites, Dev Mode, FigJam, and Figma Slides.": "{planName} 中的完整席位包含更高的 MCP 工具调用上限，并可完整使用 Figma Weave、Figma Make、Figma Design、Figma Sites、Dev Mode、FigJam 和 Figma Slides。",
"You’ve been invited to edit this Figma Weave file. This will update your seat in {planName}—you’ll get full access to Figma Weave, Figma Make, Figma Design, Figma Sites, Dev Mode, FigJam, and Figma Slides.": "您已受邀编辑此 Figma Weave 文件。这将更新您在 {planName} 中的席位—您将可以完整使用 Figma Weave、Figma Make、Figma Design、Figma Sites、Dev Mode、FigJam 和 Figma Slides。",
"You’re about to get full access to {licenseType}!": "您即将获得 {licenseType} 的完整访问权限！",
"Move to a {seatName} seat for more AI credits": "改用 {seatName} 席位以获得更多 AI 点数",
"Move to a {seatName} seat for more MCP tool calls": "改用 {seatName} 席位以获得更多 MCP 工具调用次数",
"{fileName} is already opened in another tab. Continue editing in that tab, or close it before opening here.": "{fileName} 已在另一个标签页中打开。请在该标签页中继续编辑，或先关闭它再在此处打开。",
"There are unsynced changes to {fileName} from when you were offline. Open the file to sync the changes.": "您离线期间对 {fileName} 的更改尚未同步。打开文件以同步更改。",
"Changes you made to {fileName} while offline haven't synced yet.": "您离线期间对 {fileName} 所做的更改尚未同步。",
"{editLabel}, custom image uploaded": "{editLabel}，已上传自定义图像",
"{editLabel}, no image uploaded": "{editLabel}，未上传图像",
"People at {creditLimitText}": "人员：{creditLimitText}",
"To edit this Education team file from {teamName}, verify that you're a student or educator.": "要编辑来自 {teamName} 的教育版团队文件，请验证您是学生或教育工作者。",
"A new version of {editorType} is available": "{editorType} 有新版本可用",
"Ask any {orgName} admin to move it into a different project.": "请让 {orgName} 的任一管理员将其移至其他项目。",
"Ask any {orgName} admin to move it into a different folder.": "请让 {orgName} 的任一管理员将其移至其他文件夹。",
"Ask any {teamName} admin to move it into a different project.": "请让 {teamName} 的任一管理员将其移至其他项目。",
"Ask any {teamName} admin to move it into a different folder.": "请让 {teamName} 的任一管理员将其移至其他文件夹。",
"{teamName} added new paid seats after the subscription was cancelled. To restore access, please ask your team admin to reactivate the subscription or downgrade some people's seats.": "{teamName} 在订阅取消后新增了付费席位。要恢复访问权限，请让团队管理员重新激活订阅或减少部分席位。",
"{planName} members who run out of seat credits can use these credits. They’ll reset each month until your plan renewal.": "{planName} 中用完席位额度的成员可以使用这些点数。点数会在套餐续订前每月重置。",
"Please pay outstanding invoices to add credits to {planName}.": "请支付未结发票，以便向 {planName} 添加点数。",
"Update how many credits {planName} members share each month, or add a new pay as you go budget for some extra flexibility.": "更新 {planName} 成员每月共享的点数，或为部分成员添加新的按量付费预算，以获得更大灵活性。",
"Update how many credits {planName} members share each month, or edit your pay as you go budget for extra flexibility.": "更新 {planName} 成员每月共享的点数，或编辑您的按量付费预算，以获得更大灵活性。",
"Update how many credits {planName} members share each month.": "更新 {planName} 成员每月共享的点数。",
"Maximum budget: {priceString}/mo": "最高预算：{priceString}/月",
"Minimum budget: {priceString}/mo": "最低预算：{priceString}/月",
"Monthly maximum set to {priceString}/mo": "每月最高额度已设为 {priceString}",
"Failed to save credits for {billingGroupName}": "保存 {billingGroupName} 的点数失败",
"Credits for {billingGroupName} saved": "{billingGroupName} 的点数已保存",
"This will assign {percentage}% of your organization’s credits.": "这将分配组织点数的 {percentage}%。",
"Assign AI credits to {billingGroupName}": "为 {billingGroupName} 分配 AI 点数",
"{billingGroupName} will only use your organization’s paid monthly credits moving forward.": "{billingGroupName} 今后只会使用您组织的每月付费点数。",
"{billingGroupName} will only use your organization’s AI credits moving forward.": "{billingGroupName} 今后只会使用您组织的 AI 点数。",
"Manage credits for {billingGroupName}": "管理 {billingGroupName} 的点数",
"{billingGroupName} will not have access to any paid credits moving forward.": "{billingGroupName} 今后将无法使用任何付费点数。",
"New billing group ''{workspaceName}'' created": "已创建名为“{workspaceName}”的新账单组",
"Updated ''{workspaceName}'' billing group": "已更新“{workspaceName}”账单组",
"New available font: {firstFont}": "新可用字体：{firstFont}",
"{propertyLabel} applied": "{propertyLabel} 已应用",
"{propertyLabel} modified": "{propertyLabel} 已修改",
"{propertyLabel} removed": "{propertyLabel} 已移除",
"Add template {name}": "添加模板 {name}",
"{entityName} templates": "{entityName} 模板",
"See all {categoryTitle}": "查看全部 {categoryTitle}",
"Use template {name}": "使用模板 {name}",
"Preview thumbnail for exporting asset {name}": "预览要导出的资源 {name} 的缩略图",
"{processName} finished.": "{processName} 已完成。",
"{processName} started.": "{processName} 已开始。",
"Choose a seat type for everyone in {teamName}.": "为 {teamName} 中的所有人选择席位类型。",
"Last edited {relativeTime}": "上次编辑于 {relativeTime}",
"See all files in {projectName}": "查看 {projectName} 中的所有文件",
"Click to connect to {collectionName}": "点击以连接到 {collectionName}",
"Click to connect webpage to {collectionName}": "点击以将网页连接到 {collectionName}",
"Click to connect to {fieldName}": "点击以连接到 {fieldName}",
"Archive {branchName}": "归档 {branchName}",
"Copy link to {branchName}": "复制 {branchName} 的链接",
"Send {nodeName} to Figma Buzz": "将 {nodeName} 发送到 Figma Buzz",
"Send {numSelectedNodes} selected to Figma Buzz": "将选中的 {numSelectedNodes} 个对象发送到 Figma Buzz",
"Pick {option} changes for all conflicts": "为所有冲突选择 {option} 更改",
"Color stop {index}": "颜色停靠点 {index}",
"Leave a comment for {ownerHandle} (optional)": "为 {ownerHandle} 留下评论（可选）",
"Leave a comment for {ownerHandle} and other reviewers (optional)": "为 {ownerHandle} 和其他审阅者留下评论（可选）",
"Conflicts with {sourceFileName} must be resolved to merge this branch": "必须解决与 {sourceFileName} 的冲突才能合并此分支",
"Merging {branchName} changes": "正在合并 {branchName} 的更改",
"You don't have edit access in {fileName}, so you can't merge this yourself. We suggest adding someone with edit access here.": "您没有 {fileName} 的编辑权限，因此无法自行合并。建议在此处添加拥有编辑权限的人员。",
"You don't have edit access in {fileName}, so you can't merge this yourself. We suggest adding one of these people with edit access:": "您没有 {fileName} 的编辑权限，因此无法自行合并。建议添加以下任一拥有编辑权限的人员：",
"Only editors of {sourceFileName} can merge this branch": "只有 {sourceFileName} 的编辑者才能合并此分支",
"You are able to merge this branch, along with other editors of {sourceFileName}": "您可以与 {sourceFileName} 的其他编辑者一起合并此分支",
"New branch {link} created": "已创建新分支 {link}",
"Branch {link} updated from main file": "已根据主文件更新分支 {link}",
"Branch merged into {link} and archived": "分支已合并到 {link} 并归档",
"Branch updated from {link}": "已根据 {link} 更新分支",
"{versionText} (linked version)": "{versionText}（关联版本）",
"Press {shortcut} to add to version history while editing.": "编辑时按 {shortcut} 添加到版本历史记录。",
"Version editors, {numEditors} total": "版本编辑者，共 {numEditors} 人",
"Restored version: {label}": "已恢复版本：{label}",
"Viewing {label}": "正在查看 {label}",
"Just click {spotlightMeButtonText} in the dropdown to lead your teammates around the file.": "只需点击下拉菜单中的 {spotlightMeButtonText}，即可带领队友浏览文件。",
"Dismiss request to spotlight from {nominatorName}": "忽略 {nominatorName} 发起的聚光灯请求",
"Take over spotlight from {currentPresenter}": "接管 {currentPresenter} 的聚光灯",
"Following {observedUserName}": "正在关注 {observedUserName}",
"{nominatorName} is asking you to spotlight": "{nominatorName} 请求您开启聚光灯",
"Switching to {presenterName}…": "正在切换到 {presenterName}…",
"Stop following {observedUserName}": "停止关注 {observedUserName}",
"Asked {userName} to spotlight": "已请求 {userName} 开启聚光灯",
"{userName} left the spotlight": "{userName} 已退出聚光灯",
"Click to follow {username}": "点击关注 {username}",
"Click to unfollow {username}": "点击取消关注 {username}",
"Add this ID to your {filename} file": "将此 ID 添加到您的 {filename} 文件中",
"Add up to {maxCreatorsPerResource} additional creators": "最多添加 {maxCreatorsPerResource} 位其他创作者",
"Add up to {maxMedia} images and videos to your carousel": "轮播中最多添加 {maxMedia} 张图片和视频",
"Add up to {maxMedia} images to your carousel": "轮播中最多添加 {maxMedia} 张图片",
"Add up to {maxTagsPerResource} more tags, separated by commas or tabs": "最多再添加 {maxTagsPerResource} 个标签，以逗号或制表符分隔",
"Add up to {maxTagsPerResource} tags, separated by commas or tabs": "最多添加 {maxTagsPerResource} 个标签，以逗号或制表符分隔",
"Cover art image exceeds max size of {maxResourceSize}MB": "封面图片超过 {maxResourceSize}MB 的最大大小",
"Publishing on Community is subject to the {creatorAgreement}.": "在社区发布须遵守 {creatorAgreement}。",
"Description must be at most {maxLength} characters long": "描述最多只能包含 {maxLength} 个字符",
"{filename} not found": "找不到 {filename}",
"{filename} must be a jpeg or png": "{filename} 必须是 jpeg 或 png 文件",
"{filename} must be mp4, webm, or quicktime": "{filename} 必须是 mp4、webm 或 quicktime 文件",
"Failed to read {filename}": "读取 {filename} 失败",
"Give up to {maxCreatorsPerResource} creators credit by name or @username": "最多为 {maxCreatorsPerResource} 位创作者标注姓名或 @用户名",
"I agree to the {termsOfService}": "我同意 {termsOfService}",
"Invalid ID in {filename}": "{filename} 中的 ID 无效",
"Kit will be published to {entityName}": "工具包将发布到 {entityName}",
"Name must be at most {maxLength} characters long": "名称最多只能包含 {maxLength} 个字符",
"Name must be at least {minLength} characters long": "名称至少需要包含 {minLength} 个字符",
"Review issues ({count})": "查看问题（{count}）",
"Ready to publish ({count})": "可以发布（{count}）",
"Changes to publish ({count})": "待发布的更改（{count}）",
"No changes ({count})": "没有更改（{count}）",
"Please add this to your {filename} file": "请将此内容添加到您的 {filename} 文件中",
"Let people try out your resource in a playground file. Create your own or {useTemplateLink}": "让用户在演示文件中试用您的资源。创建自己的演示文件，或{useTemplateLink}",
"{errorStringPrefix} cannot be empty": "{errorStringPrefix}不能为空",
"Profile handle cannot be longer than {maxLength} characters": "个人资料用户名不能超过 {maxLength} 个字符",
"Publish to the {lineBreak} Figma Community": "发布到 {lineBreak} Figma 社区",
"Select up to {maxTagsPerResource} tags to help people discover your resource": "最多选择 {maxTagsPerResource} 个标签，帮助用户发现您的资源",
"Select up to {maxTagsPerResource} tags": "最多选择 {maxTagsPerResource} 个标签",
"A skill with this name already exists in {planName}.": "{planName} 中已存在同名技能。",
"Support contact must be at most {maxLength} characters long": "支持联系方式最多只能包含 {maxLength} 个字符",
"{tag} tag is repeated more than once": "{tag} 标签重复出现",
"{tag} is not a valid value from the list": "{tag} 不是列表中的有效值",
"Use up to {maxLength} characters (letters, numbers, or _)": "最多使用 {maxLength} 个字符（字母、数字或 _）",
"You can add up to {maxTagsPerResource} custom tags": "最多添加 {maxTagsPerResource} 个自定义标签",
"You can only upload up to {maxMedia} images. Please update.": "最多只能上传 {maxMedia} 张图片。请更新。",
"You can only upload up to {maxMedia} images and videos. Please update.": "最多只能上传 {maxMedia} 张图片和视频。请更新。",
"You can only upload up to {maxVideos} videos. Please update.": "最多只能上传 {maxVideos} 个视频。请更新。",
"Update instances of {componentName}": "更新 {componentName} 的实例",
"Updates to components, styles, or variables{lineBreak}will show up here as they become available.": "对组件、样式或变量的更新{lineBreak}将在可用时显示在这里。",
"Opened “{fileName}” in Figma app": "已在 Figma 应用中打开“{fileName}”",
"Opening “{fileName}” in Figma app…": "正在 Figma 应用中打开“{fileName}”…",
"Your Figma desktop app needs an update to continue working. Get the latest version from our {downloadsPageLink}.": "您的 Figma 桌面应用需要更新才能继续使用。请从{downloadsPageLink}获取最新版本。",
"{language} code": "{language} 代码",
"Scale factor for scaling pixels into {unitName} units": "将像素缩放为 {unitName} 单位的缩放因子",
"Unit: {unit}": "单位：{unit}",
"Only apply {rem} on text properties": "仅在文本属性上应用 {rem}",
"Use {scaledUnit}": "使用 {scaledUnit}",
"This will stop {currentAutoRunPluginName} from running automatically when you open a file.": "打开文件时，{currentAutoRunPluginName} 将不再自动运行。",
"Enable auto run for {pluginName}?": "要为 {pluginName} 启用自动运行吗？",
"Values are relative to parent ({name})": "值相对于父级（{name}）",
"{value} is typically used in iOS and isn’t available in browsers yet. Try another design solution for broader browser compatibility.": "{value} 通常用于 iOS，目前尚未在浏览器中提供。请尝试其他设计方案，以获得更广泛的浏览器兼容性。",
"Language: {codeLanguage}": "语言：{codeLanguage}",
"Unit: {unit} and preferences": "单位：{unit} 和偏好设置",
"Go to parent component: {name}": "转到父组件：{name}",
"{componentName} was connected": "{componentName} 已连接",
"{componentName} was disconnected": "{componentName} 已断开连接",
"Skipped {componentName}": "已跳过 {componentName}",
"Improve MCP server performance by connecting design components to your codebase. {value}": "将设计组件连接到代码库，提升 MCP 服务器性能。{value}",
"Publish components to a library, then you can connect them to your codebase with Code Connect. {value}": "将组件发布到组件库，然后即可使用 Code Connect 将其连接到代码库。{value}",
"Removed Skipped from {componentName}": "已从 {componentName} 移除“已跳过”状态",
"Storybook connection for {componentName} deleted": "已删除 {componentName} 的 Storybook 连接",
"No layer with id \"{codeConnectId}\" found in selected component/variant": "在所选组件/变体中找不到 ID 为“{codeConnectId}”的图层",
"Child layer named \"{layerName}\" not found in selected component/variant": "在所选组件/变体中找不到名为“{layerName}”的子图层",
"Property \"{propertyName}\" not found. The design file might not be using the latest version of the design library": "找不到属性“{propertyName}”。设计文件可能未使用设计库的最新版本",
"Code Connect is not set up for this component. {learnMore}": "此组件尚未设置 Code Connect。{learnMore}",
"Your org has set up Code Connect, and this component does not exist in your codebase. {learnMore}": "您的组织已设置 Code Connect，但代码库中不存在此组件。{learnMore}",
"Unit (for {languageOrPlugin})": "单位（用于 {languageOrPlugin}）",
"{org_name} doesn’t allow team members to create their own connectors.": "{org_name} 不允许团队成员创建自己的连接器。",
"Publish to {org_name}": "发布到 {org_name}",
"{server_name} connector": "{server_name} 连接器",
"Unpublish {server_name}?": "要取消发布 {server_name} 吗？",
"This connector will no longer be available to {org_name} users in Figma.": "此连接器将不再对 Figma 中的 {org_name} 用户可用。",
"Unpublished {server_name}": "已取消发布 {server_name}",
"{server_name} tool cancelled": "{server_name} 工具调用已取消",
"{server_name} connection cancelled": "{server_name} 连接已取消",
"Connect to {server_name}": "连接到 {server_name}",
"{server_name} connected": "{server_name} 已连接",
"Each organization gets two free active projects. To connect a new one, pause an active project or {upgradeLink}.": "每个组织可免费拥有两个活跃项目。要连接新项目，请暂停一个活跃项目或{upgradeLink}。",
"Max height: {value}": "最大高度：{value}",
"Max width: {value}": "最大宽度：{value}",
"Min height: {value}": "最小高度：{value}",
"Min width: {value}": "最小宽度：{value}",
"Generate image: {prompt}": "生成图像：{prompt}",
"Task {number}": "任务 {number}",
"Previewing version {version}": "正在预览版本 {version}",
"Publishing failed while running {scriptPath}. Ask the agent to fix this for you then try again.": "运行 {scriptPath} 时发布失败。请让智能体为您修复，然后重试。",
"Published! Your app is live at {domain}": "已发布！您的应用已上线：{domain}",
"You can send up to {maxAttachments} nodes to Figma Make at a time": "您每次最多可以向 Figma Make 发送 {maxAttachments} 个节点",
"Pasting your selection from {editorType}": "正在从 {editorType} 粘贴您的选区",
"Check within the next few weeks for AI prompting. {learnMoreLink}": "未来几周内请留意 AI 提示功能。{learnMoreLink}",
"Figma Make is not currently available on your plan. {learnMoreLink}": "您的套餐目前无法使用 Figma Make。{learnMoreLink}",
"Figma Make is currently only available to Full seats. {learnMoreLink}": "Figma Make 目前仅供完整席位使用。{learnMoreLink}",
"You don’t have access to this feature. {learnMoreLink}": "您无权使用此功能。{learnMoreLink}",
"Collapse heading {level}": "折叠标题 {level}",
"Expand heading {level}": "展开标题 {level}",
"Rename file {fileName}": "重命名文件 {fileName}",
"Anyone at {orgName}": "{orgName} 中的任何人",
"Anyone at {orgName} with the link": "{orgName} 中拥有链接的任何人",
"You don't have permission to create projects in {teamName}.": "您没有在 {teamName} 中创建项目的权限。",
"You don’t have permission to create folders in {teamName}.": "您没有在 {teamName} 中创建文件夹的权限。",
"Projects set as invite-only cannot be moved between teams. To complete this operation, enable team access for {projectName} and retry.": "设置为仅限受邀者访问的项目无法在团队之间移动。要完成此操作，请为 {projectName} 启用团队访问权限，然后重试。",
"Folders set as invite-only cannot be moved between teams. To complete this operation, enable team access for {projectName} and retry.": "设置为仅限受邀者访问的文件夹无法在团队之间移动。要完成此操作，请为 {projectName} 启用团队访问权限，然后重试。",
"Projects set as view-only cannot be moved between teams. To complete this operation, enable team edit access for {projectName} and retry.": "设置为仅限查看的项目无法在团队之间移动。要完成此操作，请为 {projectName} 启用团队编辑权限，然后重试。",
"Folders set as view-only cannot be moved between teams. To complete this operation, enable team edit access for {projectName} and retry.": "设置为仅限查看的文件夹无法在团队之间移动。要完成此操作，请为 {projectName} 启用团队编辑权限，然后重试。",
"The file {fileNameText} is currently published as a library, which means:": "文件 {fileNameText} 当前已作为组件库发布，这意味着：",
"Are you sure you want to delete {fileName} forever?": "确定要永久删除 {fileName} 吗？",
"You're about to permanently delete the project {folderName} and all of its files.": "您即将永久删除项目 {folderName} 及其中的所有文件。",
"You’re about to permanently delete the folder {folderName} and all of its files.": "您即将永久删除文件夹 {folderName} 及其中的所有文件。",
"You can only drag and drop files created in {planName}": "您只能拖放在 {planName} 中创建的文件",
"You can only drag and drop folders created in {planName}": "您只能拖放在 {planName} 中创建的文件夹",
"You can only drag and drop teams created in {planName}": "您只能拖放在 {planName} 中创建的团队",
"Are you sure you want to move these files? Members of {projectName} may lose access to some of them": "确定要移动这些文件吗？{projectName} 的成员可能会失去其中部分文件的访问权限",
"An error occurred while logging out of {emailAddress}": "退出 {emailAddress} 时出错",
"You don't have permission to remove files from {projectName}": "您没有从 {projectName} 移除文件的权限",
"Successfully logged out of {emailAddress}": "已成功退出 {emailAddress}",
"New {fileType} file": "新建 {fileType} 文件",
"Imported to {folderName}": "已导入到 {folderName}",
"Current location: {projectName}": "当前位置：{projectName}",
"These files are already in {folderName}": "这些文件已位于 {folderName} 中",
"Moving “{fileName}” into this project may result in viewers losing or gaining access based on the permissions within this project.": "将“{fileName}”移入此项目后，查看者的访问权限可能会根据项目中的权限发生变化。",
"Moving “{fileName}” into this folder may result in viewers losing or gaining access based on the permissions within this folder.": "将“{fileName}”移入此文件夹后，查看者的访问权限可能会根据文件夹中的权限发生变化。",
"Move {folderName} to a new team or folder to restore it.": "将 {folderName} 移动到新团队或文件夹以恢复它。",
"Restore {fileName}": "恢复 {fileName}",
"No project or team results matching {query}": "没有找到与 {query} 匹配的项目或团队",
"No folder or team results matching {query}": "没有找到与 {query} 匹配的文件夹或团队",
"Open {folderName}": "打开 {folderName}",
"{userHandle}'s Drafts": "{userHandle} 的草稿",
"{userHandle}'s project": "{userHandle} 的项目",
"To move this file, you need to be granted edit access to {projectName}.": "要移动此文件，您需要获得 {projectName} 的编辑权限。",
"Move project {folderName}": "移动项目 {folderName}",
"Move folder {folderName}": "移动文件夹 {folderName}",
"Restore project {folderName}": "恢复项目 {folderName}",
"Restore folder {folderName}": "恢复文件夹 {folderName}",
"Change access for {teamName}": "更改 {teamName} 的访问权限",
"{teamName} members": "{teamName} 成员",
"Go back to {pageName}": "返回 {pageName}",
"Go to {pageName}": "转到 {pageName}",
"All {maxFreePages} free pages used.": "已用完全部 {maxFreePages} 个免费页面。",
"{pageName} more actions": "{pageName} 更多操作",
"{plugin} is running in the background": "{plugin} 正在后台运行",
"Inserting {plugin}": "正在插入 {plugin}",
"Running {plugin}": "正在运行 {plugin}",
"{plugin} stopped running.": "{plugin} 已停止运行。",
"{standard} Contrast standard met.": "已符合 {standard} 对比度标准。",
"AA · Essential ({contrastValue} : 1)": "AA · 基本（{contrastValue} : 1）",
"AAA · Highest ({contrastValue} : 1)": "AAA · 最高（{contrastValue} : 1）",
"Color contrast ratio: {ratio}:1. View details": "颜色对比度：{ratio}:1。查看详情",
"Edit {name} brush": "编辑 {name} 画笔",
"~{kb} KB total": "约 {kb} KB，总计",
"~{mb} MB": "约 {mb} MB",
"~{mb} MB total": "约 {mb} MB，总计",
"{documentColorProfile} (same as file)": "{documentColorProfile}（与文件相同）",
"{fps} fps": "{fps} 帧/秒",
"Upload a shared font for anyone at {orgName} to use.": "上传共享字体，供 {orgName} 中的任何人使用。",
"Press {cmd} to select an option.": "按 {cmd} 选择选项。",
"Container ({parentName})": "容器（{parentName}）",
"When you open this link, your email {email} may be visible to other people who have access to the file": "打开此链接时，您的邮箱 {email} 可能会对其他有权访问该文件的人员可见",
"Missing font: {fontName}": "缺少字体：{fontName}",
"On the Organization plan, fonts can be shared with all your teams. {upgradeLink}": "使用组织版套餐时，字体可以与您的所有团队共享。{upgradeLink}",
"Upgrade to the Organization plan to share fonts with all your teams. {learnMoreLink}": "升级到组织版套餐，与您的所有团队共享字体。{learnMoreLink}",
"Select replacement for {fontName}": "为 {fontName} 选择替代字体",
"Some fonts were uploaded for publishing. Install their OTF/TTF files to edit. {learnMoreLink}": "部分字体已上传用于发布。请安装其 OTF/TTF 文件以进行编辑。{learnMoreLink}",
"Editing is disabled until your request to join the {orgName} organization is approved": "在您加入 {orgName} 组织的请求获批准前，编辑功能将被禁用",
"{link} to start using variable fonts and enable future automatic updates": "{link}，开始使用可变字体并启用未来的自动更新",
"{numNodes} layers deleted": "已删除 {numNodes} 个图层",
"Ask Figma {query}": "询问 Figma：{query}",
"Comment ({count} unread)": "评论（{count} 条未读）",
"Convert {format} to text": "将 {format} 转换为文本",
"Copy email {email}": "复制邮箱 {email}",
"Copy phone {number}": "复制电话 {number}",
"Expand panel for file named {fileName}": "展开名为 {fileName} 的文件面板",
"Expand UI for file named {fileName}": "展开名为 {fileName} 的文件界面",
"Plugins from {orgName}": "来自 {orgName} 的插件",
"Invite other members to {orgName}": "邀请其他成员加入 {orgName}",
"Invite people to {orgName}": "邀请人员加入 {orgName}",
"Add {requesterName} to your organization?": "要将 {requesterName} 添加到您的组织吗？",
"{requesterName} has been added to your organization": "已将 {requesterName} 添加到您的组织",
"You are already the admin of a Figma Organization plan. If you need another Organization plan, please {contactSales}.": "您已经是 Figma 组织版套餐的管理员。如果您需要另一个组织版套餐，请{contactSales}。",
"Have questions? {contactSales}": "有疑问？{contactSales}",
"Let people use Figma's AI features in all files in your organization. {learnMore}": "允许用户在组织中的所有文件里使用 Figma 的 AI 功能。{learnMore}",
"Let people use Figma's AI features in all files in your workspace. {learnMore}": "允许用户在工作区中的所有文件里使用 Figma 的 AI 功能。{learnMore}",
"{workspaceName} will go back to using the default settings for AI features.": "{workspaceName} 将恢复使用 AI 功能的默认设置。",
"Asset approvals settings for {workspaceName}": "{workspaceName} 的资源审批设置",
"{workspaceName} will go back to using the default settings for asset approvals behavior.": "{workspaceName} 将恢复使用资源审批行为的默认设置。",
"Choose who’s allowed to export from your organization’s files. {learnMoreLink}": "选择谁可以从组织的文件中导出内容。{learnMoreLink}",
"{workspaceName} will go back to using the default settings for file exporting.": "{workspaceName} 将恢复使用文件导出的默认设置。",
"This setting affects people's access to content, so you may want to {let_org_know} before making updates.": "此设置会影响人员对内容的访问，因此您可能需要在更新前{let_org_know}。",
"When you allow members to access content from outside {orgName}, they can:": "当您允许成员访问来自 {orgName} 外部的内容时，他们可以：",
"Members can access content from outside {orgName}": "成员可以访问来自 {orgName} 外部的内容",
"Guests are external users without an {domains} address.": "访客是不具有 {domains} 地址的外部用户。",
"New guests can view and edit files in {orgName} until their access expires. This will not change access for existing guests.": "新访客可以在访问权限到期前查看和编辑 {orgName} 中的文件。这不会改变现有访客的访问权限。",
"Guests without 2FA will be blocked from {orgName}.": "没有启用双重身份验证的访客将被禁止访问 {orgName}。",
"Leave {orgName} organization": "退出 {orgName} 组织",
"Members without 2FA will be blocked from logging in. {learnMoreLink}": "没有启用双重身份验证的成员将无法登录。{learnMoreLink}",
"Email: {userEmail}": "邮箱：{userEmail}",
"User: {userName}": "用户：{userName}",
"Generated {timestamp}": "生成于 {timestamp}",
"I understand that any API requests made using the API token {willBeDenied}.": "我了解使用 API 令牌{willBeDenied}发出的任何 API 请求。",
"SCIM allows you to automatically update, provision, and deprovision users. For more information, view this {helpArticle}.": "SCIM 允许您自动更新、配置和取消配置用户。有关详细信息，请查看此{helpArticle}。",
"SAML single sign-on allows you to manage your users with a third-party identity provider (IdP). For more information, view this {helpArticle}.": "SAML 单点登录允许您使用第三方身份提供商（IdP）管理用户。有关详细信息，请查看此{helpArticle}。",
"Who can create teams in {organization}": "谁可以在 {organization} 中创建团队",
"View {workspaceName} settings": "查看 {workspaceName} 设置",
"{workspaceName} will go back to using the default web publishing settings.": "{workspaceName} 将恢复使用网页发布的默认设置。",
"You successfully left {orgName} Organization.": "您已成功退出 {orgName} 组织。",
"No {resourceType} have been published to this organization yet.": "此组织尚未发布任何 {resourceType}。",
"Search {resourceType}…": "搜索 {resourceType}…",
"No {resourceType} match your search query. Try your search again.": "没有与搜索查询匹配的 {resourceType}。请重新搜索。",
"No {resourceType} match your search or filter. Try adjusting your search or filter.": "没有与搜索或筛选条件匹配的 {resourceType}。请调整搜索或筛选条件。",
"Make this {resourceType} available for users by default": "默认向用户提供此 {resourceType}",
"Highlight this {resourceType} for users in your workspaces": "为工作区中的用户突出显示此 {resourceType}",
"Recommend to all {orgName}": "向所有 {orgName} 用户推荐",
"Recommend {resourceName}": "推荐 {resourceName}",
"This {resourceType} is already recommended to the organization": "此 {resourceType} 已向组织推荐",
"No fonts match your search query. Try your search again or {uploadFontsLink}.": "没有字体与搜索查询匹配。请重新搜索或{uploadFontsLink}。",
"Type: {fileType}": "类型：{fileType}",
"wants to {requestType}": "希望{requestType}",
"Partial file saved {date}": "部分文件已保存于 {date}",
"No file, project, team, or people results matching {searchQuery}": "没有找到与 {searchQuery} 匹配的文件、项目、团队或人员",
"No file, folder, team, or people results matching {searchQuery}": "没有找到与 {searchQuery} 匹配的文件、文件夹、团队或人员",
"By: {creator}": "作者：{creator}",
"In: {space}": "位置：{space}",
"Active {relativeTimeString}": "活跃于 {relativeTimeString}",
"In {teamName}": "位于 {teamName}",
"All {orgName}": "全部 {orgName}",
"Last active {relativeTimeString}": "最后活跃于 {relativeTimeString}",
"To upgrade or add new seats, {cta}.": "要升级或添加新席位，请{cta}。",
"Your {seatType} seat request is in.": "您的 {seatType} 席位请求已提交。",
"Tooltip image showing the product {productKey}": "显示产品 {productKey} 的工具提示图像",
"We’ll send your request to an admin at {orgOrTeamName}.": "我们会将您的请求发送给 {orgOrTeamName} 的管理员。",
"Cannot update email - \"{tokenId}\" is already taken": "无法更新邮箱——“{tokenId}”已被占用",
"{workspaceName} will go back to using the default settings for public sharing.": "{workspaceName} 将恢复使用公开共享的默认设置。",
"If your new email doesn’t end in @{orgDomain}, you may lose access to some or all of your organization’s files.": "如果您的新邮箱不是以 @{orgDomain} 结尾，您可能会失去部分或全部组织文件的访问权限。",
"Two-factor authentication (2FA) required for {orgName}": "{orgName} 要求启用双重身份验证（2FA）",
"{enableLibrariesLink} for all files in your drafts": "对草稿中的所有文件{enableLibrariesLink}",
"Learn more about captioning {learnMoreLink}": "详细了解字幕功能{learnMoreLink}",
"Local fonts are enabled. You have {localFontCount} fonts available in Figma.": "本地字体已启用。您在 Figma 中有 {localFontCount} 种可用字体。",
"For more information about how we treat your data, please see our {privacyPolicyLink}.": "有关我们如何处理您的数据的更多信息，请参阅我们的{privacyPolicyLink}。",
"To confirm, please type \"{confirmationText}\" below.": "要确认，请在下方输入“{confirmationText}”。",
"{orgHandle} currently has no restricted commenters.": "{orgHandle} 当前没有受限评论者。",
"Can't load collection. Restore a previous version in its originating file, or {link}.": "无法加载组件库。请在其源文件中恢复以前的版本，或{link}。",
"Can't load collection. Restore a previous version of this file, or {link}.": "无法加载组件库。请恢复此文件的以前版本，或{link}。",
"No fonts found for \"{fontFamily}\"": "找不到“{fontFamily}”的字体",
"Collection name changed to {collectionName}": "组件库名称已更改为 {collectionName}",
"Modes changed to {modeNames}": "模式已更改为 {modeNames}",
"Color Variable {variableName}": "颜色变量 {variableName}",
"Collections can't have more than {variableLimit} variables": "组件库不能包含超过 {variableLimit} 个变量",
"Some layers need updates before they can use {modeName}.": "部分图层需要更新后才能使用 {modeName}。",
"Library assets may need to be republished for {modeName} mode to show.": "可能需要重新发布组件库资源，才能显示 {modeName} 模式。",
"Search results for ’{query}’": "“{query}”的搜索结果",
"{adminTeamName} Admin Console": "{adminTeamName} 管理控制台",
"Upgrade {teamName}": "升级 {teamName}",
"Enter full screen ({shortcut})": "进入全屏（{shortcut}）",
"Exit full screen ({shortcut})": "退出全屏（{shortcut}）",
"Actual size ({zoomAmount}%)": "实际大小（{zoomAmount}%）",
"Show device at {zoomAmount}%": "以 {zoomAmount}% 显示设备",
"Press {keycommand} to show the Figma UI again": "按 {keycommand} 再次显示 Figma 界面",
"Are you sure you want to delete Session {sessionNumber}?": "确定要删除会话 {sessionNumber} 吗？",
"Recording Session {sessionNumber}": "正在录制会话 {sessionNumber}",
"Session {sessionNumber}": "会话 {sessionNumber}",
"To collaborate with {fileOpenerName} and other teammates in this draft, you’ll need an upgraded seat.": "要与 {fileOpenerName} 及其他队友在此草稿中协作，您需要升级席位。",
"{failedFileCount} files could not be added": "无法添加 {failedFileCount} 个文件",
"{failedFileCount} file could not be added": "无法添加 {failedFileCount} 个文件",
"Can't paste {typeName} from FigJam to Buzz files": "无法将 {typeName} 从 FigJam 粘贴到 Buzz 文件",
"Can't paste {typeName} from FigJam to Design files": "无法将 {typeName} 从 FigJam 粘贴到 Design 文件",
"Can't paste {typeName} from FigJam to Sites files": "无法将 {typeName} 从 FigJam 粘贴到 Sites 文件",
"Copied {colorType}": "已复制 {colorType}",
"Copy as {fileType} failed | Try again": "复制为 {fileType} 失败 | 重试",
"Copied email {email}": "已复制邮箱 {email}",
"Copied link to {hyperlink}": "已复制指向 {hyperlink} 的链接",
"Copied link to {format}": "已复制指向 {format} 的链接",
"Copied phone {number}": "已复制电话 {number}",
"There is an error syncing the code on {codeFileName}.": "同步 {codeFileName} 上的代码时出错。",
"Moved to {folderName}": "已移动到 {folderName}",
"Forced layout of {count} text elements": "已强制排列 {count} 个文本元素",
"Height set to Fixed for {nodes}": "{nodes} 的高度已设为固定",
"Height set to Hug for {nodes}": "{nodes} 的高度已设为适应内容",
"Horizontal constraint set to Center for {nodes}": "{nodes} 的水平约束已设为居中",
"Image file {filename} import failed": "图像文件 {filename} 导入失败",
"To use Figma for VS Code, you’ll need access to {devMode}.": "要使用 Figma for VS Code，您需要访问 {devMode}。",
"{button} to show full title": "{button} 以显示完整标题",
"Layers, selected layer \"{layer}\"": "图层，已选择图层“{layer}”",
"Latest: {activityTime}": "最新：{activityTime}",
"{count} layers selected": "已选择 {count} 个图层",
"Collapse {pageName}": "折叠 {pageName}",
"Expand {pageName}": "展开 {pageName}",
"Thumbnail of \"{imageDescription}\"": "“{imageDescription}”的缩略图",
"{suggestion}, AI agent": "{suggestion}，AI 智能体",
"Design from {makeName} has been edited": "来自 {makeName} 的设计已编辑",
"Extracted from {makeName}": "已从 {makeName} 提取",
"Search the {packageName} Design System": "搜索 {packageName} 设计系统",
"More templates from {planName}": "来自 {planName} 的更多模板",
"Recommended templates from {planName}": "来自 {planName} 的推荐模板",
"Failed to upload file \"{name}\"": "上传文件“{name}”失败",
"This will delete \"{folderName}\" and all files and folders within it.": "这将删除“{folderName}”及其中的所有文件和文件夹。",
"Delete \"{folderName}\"? This can't be undone.": "要删除“{folderName}”吗？此操作无法撤销。",
"Folder \"{name}\"": "文件夹“{name}”",
"Options for {accountName}": "{accountName} 的选项",
"Publishing failed: {scriptPath} script not found. Ask the agent to fix this for you then try again.": "发布失败：找不到 {scriptPath} 脚本。请让智能体为您修复，然后重试。",
"Earlier changes {index}": "较早的更改 {index}",
"Recent turns, {range}": "最近的轮次，{range}",
"{name}’s organization": "{name} 的组织",
"{name}’s project": "{name} 的项目",
"Couldn’t find templates matching \"{searchTerm}\"": "找不到与“{searchTerm}”匹配的模板",
"Close {tabName}": "关闭 {tabName}",
"Shell exited with status {exitCode}.": "Shell 已退出，状态码为 {exitCode}。",
"Rename {tabName}": "重命名 {tabName}",
"Back to {fileName}": "返回 {fileName}",
"Rename spec {specName}": "重命名规格 {specName}",
"See {numberOfEditableProjects} more projects": "查看另外 {numberOfEditableProjects} 个项目",
"See {numberOfEditableProjects} more folders": "查看另外 {numberOfEditableProjects} 个文件夹",
"{numFiles} files found.": "找到 {numFiles} 个文件。",
"You joined {hostName}'s collaboration": "您已加入 {hostName} 的协作",
"Remove {exampleName} from selected examples": "从选定示例中移除 {exampleName}",
"Select {exampleName} as an example": "选择 {exampleName} 作为示例",
"Remove {num_cols} columns": "移除 {num_cols} 列",
"Remove {num_rows} rows": "移除 {num_rows} 行",
"{count} slots selected": "已选择 {count} 个插槽",
"Guide {num}": "参考线 {num}",
"Remove horizontal guide {num}": "移除水平参考线 {num}",
"{nodeName} Ruler Guides": "{nodeName} 标尺参考线",
"Remove vertical guide {num}": "移除垂直参考线 {num}",
"Copy font size: {value}": "复制字体大小：{value}",
"Copy line height: {value}": "复制行高：{value}",
"Settings (for {languageOrPlugin})": "设置（用于 {languageOrPlugin}）",
"Copy link: {link}": "复制链接：{link}",
"Get instructions for your AI coding agent {hereWithHyperlink}.": "获取 AI 编程智能体的说明{hereWithHyperlink}。",
"Sent {timeFromNow}": "已发送于 {timeFromNow}",
"Generate code with context from this file via the remote MCP server. {learnMoreLink}": "通过远程 MCP 服务器使用此文件的上下文生成代码。{learnMoreLink}",
"Measurements for {layerName}": "{layerName} 的测量结果",
"Ask an admin of {teamName} about upgrading.": "请咨询 {teamName} 的管理员以了解升级事宜。",
"{host} refused to connect": "{host} 拒绝连接",
"Unpublishing {domain} will take what you've made offline. Your domain name will still be available if you choose to republish.": "取消发布 {domain} 会使您创建的内容下线。如果您选择重新发布，域名仍可使用。",
"{modifier}click a stroke to sample properties": "按住 {modifier} 并点击描边以采样属性",
"{zoomPercentage}%, zoom and view options": "{zoomPercentage}%，缩放和视图选项",
"{plugin} ran into an issue": "{plugin} 遇到问题",
"Your {orgName} admins have started updates that may take a while to complete. Check back soon, or work from another account in the meantime.": "您的 {orgName} 管理员已开始更新，可能需要一段时间才能完成。请稍后再查看，或暂时使用其他账户工作。",
"Your {orgName} admins have started updates that may take a while to complete. Check back soon.": "您的 {orgName} 管理员已开始更新，可能需要一段时间才能完成。请稍后再查看。",
"Looking for a different account? {addAnotherLink}": "要使用其他账户吗？{addAnotherLink}",
"Want to work from another account in the meantime? {addAnotherLink}": "想暂时使用其他账户工作吗？{addAnotherLink}",
"Another process is using port {port}": "另一个进程正在使用端口 {port}",
"Port {port} is in use by this folder": "此文件夹正在使用端口 {port}",
"Another tab is using port {port}": "另一个标签页正在使用端口 {port}",
"Hide output for {stepLabel}": "隐藏 {stepLabel} 的输出",
"Show output for {stepLabel}": "显示 {stepLabel} 的输出",
"Switch branch, current branch: {branch}": "切换分支，当前分支：{branch}",
"Previewing branch: {branch}": "正在预览分支：{branch}",
"{host} isn’t in your known hosts. Add it with:": "{host} 不在您的已知主机中。使用以下命令添加：",
"{host} isn’t in your known hosts and we couldn’t add it for you. Run this yourself:": "{host} 不在您的已知主机中，我们无法为您添加。请自行运行：",
"No SSH key found. You’ll need to generate one and add it to {host}.": "未找到 SSH 密钥。您需要生成一个密钥并将其添加到 {host}。",
"Could not generate component properties: {reason}": "无法生成组件属性：{reason}",
"Remote Figcode stopped unexpectedly (exit code {exitCode}).": "远程 Figcode 意外停止（退出代码 {exitCode}）。",
"Previewing: {message}": "正在预览：{message}",
"A branch named {name} already exists": "名为 {name} 的分支已存在",
"Branch name contains invalid characters or sequences ({chars})": "分支名称包含无效字符或字符序列（{chars}）",
"Start from latest {branch} on remote": "从远程的最新 {branch} 开始",
"Connection to {workspaceName} failed": "连接到 {workspaceName} 失败",
"Reconnecting to {workspaceName}": "正在重新连接到 {workspaceName}",
"Working on {workspaceName}": "正在处理 {workspaceName}",
"You’re making changes on {branch}. We recommend using a new branch instead.": "您正在 {branch} 上进行更改。建议改用新分支。",
"You need the Figma desktop app to open “{fileName}”": "您需要 Figma 桌面应用才能打开“{fileName}”",
"Opened “{fileName}” in Figma desktop app": "已在 Figma 桌面应用中打开“{fileName}”",
"Opening “{fileName}” in Figma desktop app...": "正在 Figma 桌面应用中打开“{fileName}”…",
"Last viewed {time}": "上次查看于 {time}",
"Offloaded tab: {memory}GB freed up": "已卸载标签页：释放了 {memory}GB 内存",
"Memory usage: {memory}GB": "内存占用：{memory}GB",
"About {appName}": "关于 {appName}",
"Update {appName}": "更新 {appName}",
"Blocked Navigation to ''{hostname}''": "已阻止访问“{hostname}”",
"{appName} wants to share the contents of your screen and open windows. Do you want to share your screen?": "{appName} 想要共享您的屏幕和已打开窗口的内容。是否共享屏幕？",
"\"{filePath}\" is not a valid path. No files were saved.": "“{filePath}”不是有效路径。未保存任何文件。",
"Hide {appName}": "隐藏 {appName}",
"Quit {appName}": "退出 {appName}",
"{pluginName} (Community)": "{pluginName}（社区）",
"A new version of {appName} is ready to be installed.": "{appName} 的新版本已准备好安装。",
"{appName} Reset Failed": "{appName} 重置失败",
"Reset {appName} and Restart?": "重置 {appName} 并重启？",
"Approve requests faster by {settingsLink}": "通过{settingsLink}更快地批准请求",
"No requests to show. {resetFiltersLink}": "没有可显示的请求。{resetFiltersLink}",
"Let Figma use your organization’s content to train AI models. Figma takes steps to de-identify data and protect your privacy. {learnMoreLink}": "允许 Figma 使用您组织的内容训练 AI 模型。Figma 会采取措施对数据进行去标识化并保护您的隐私。{learnMoreLink}",
"Let Figma use your team’s content to train AI models. Figma takes steps to de-identify data and protect your privacy. {learnMoreLink}": "允许 Figma 使用您团队的内容训练 AI 模型。Figma 会采取措施对数据进行去标识化并保护您的隐私。{learnMoreLink}",
"If you’d like to keep monthly seats, you can save 20% by {adding_seats_to_annual_plan_link}": "如果您想保留月度席位，可通过{adding_seats_to_annual_plan_link}节省 20%",
"Allow administrators to create and use REST API plan access tokens. {learnMoreLink}": "允许管理员创建和使用 REST API 套餐访问令牌。{learnMoreLink}",
"Allow limited viewing of content for the purpose of product support. {learnMoreLink}": "允许为产品支持目的有限查看内容。{learnMoreLink}",
"{manageSupportVisibilityLink} Support visibility": "{manageSupportVisibilityLink} 支持可见性",
"Stay on top of your team’s AI activity by tracking credit usage and seeing who’s run out. {learnMoreLink}": "通过跟踪点数使用情况并查看谁已用完点数，及时了解团队的 AI 活动。{learnMoreLink}",
"Group members may not have access to all credits. {learnMoreLink}": "组成员可能无法使用全部点数。{learnMoreLink}",
"Libraries, shared fonts, and other resources that this project used to be connected to may be unavailable after the transfer. {learnMore}": "转移后，此项目以前连接的组件库、共享字体和其他资源可能无法使用。{learnMore}",
"Libraries, shared fonts, and other resources that this folder used to be connected to may be unavailable after the transfer. {learnMore}": "转移后，此文件夹以前连接的组件库、共享字体和其他资源可能无法使用。{learnMore}",
"Libraries, shared fonts, and other resources that this team used to be connected to may be unavailable after this transfer. {learnMore}": "转移后，此团队以前连接的组件库、共享字体和其他资源可能无法使用。{learnMore}",
"This team has guest accounts. If you want them to transfer over, temporarily change your admin setting to allow guests before accepting. {learnMore}": "此团队包含访客账户。如果您希望转移这些账户，请在接受前暂时更改管理员设置以允许访客。{learnMore}",
"Once the receiving team shares their {figmaTeamLink} with you, add it here.": "接收团队与您分享其{figmaTeamLink}后，请在此处添加。",
"Once the receiving organization shares their {figmaOrgLink} with you, add it here.": "接收组织与您分享其{figmaOrgLink}后，请在此处添加。",
"If you don't see the account you want to use, you can {addAnotherLink}.": "如果没有看到要使用的账户，可以{addAnotherLink}。",
"If you're having trouble loading the Captcha puzzle, please refer to our {helpCenterLink}.": "如果加载验证码拼图时遇到问题，请参阅我们的{helpCenterLink}。",
"Wrong address? {goBackLink}": "地址错误？{goBackLink}",
"Didn't receive the code? {cta}": "没有收到验证码？{cta}",
"Wrong address? {logOutLink} to sign in with a different email.": "地址错误？{logOutLink}，使用其他邮箱登录。",
"No email in your inbox or spam folder? {resendEmailLink}.": "收件箱或垃圾邮件文件夹中没有邮件？{resendEmailLink}。",
"Your work now lives in Figma for Government. Edits made here won’t appear there. Open {figmaForGovernmentLink} to keep working.": "您的工作现在位于 Figma for Government。在此处进行的编辑不会显示在那里。打开{figmaForGovernmentLink}以继续工作。",
"Projects are no longer supported outside of teams. Please move this file to a team or your drafts to continue editing. {learnMoreLink}": "团队之外不再支持项目。请将此文件移至团队或草稿中，以继续编辑。{learnMoreLink}",
"Folders are no longer supported outside of teams. Please move this file to a team or your drafts to continue editing. {learnMoreLink}": "团队之外不再支持文件夹。请将此文件移至团队或草稿中，以继续编辑。{learnMoreLink}",
"Click on the link we sent to {emailAddress} within the next 5 minutes to log in.": "请在 5 分钟内点击我们发送至 {emailAddress} 的链接登录。",
"Click on the link we sent to {emailAddress} within the next 5 minutes to finish your account setup.": "请在 5 分钟内点击我们发送至 {emailAddress} 的链接完成账户设置。",
"If an account exists for {email}, you will get an email with instructions on resetting your password. If it doesn't arrive, be sure to check your spam folder.": "如果 {email} 已存在账户，您将收到密码重置说明邮件。如果没有收到，请检查垃圾邮件文件夹。",
"Log in or create an account to leave comments on {fileName}.": "登录或创建账户，以便在 {fileName} 上发表评论。",
"Select any organization to authenticate and access all of {email}’s organizations.": "选择任意组织进行身份验证，以访问 {email} 的所有组织。",
"Try again on the {appDescriptor} app": "在 {appDescriptor} 应用中重试",
"Your organization currently requires 2FA for all external guests. If you turn off 2FA, you won’t be able to access files in {orgName} organization unless you reactivate it.": "您的组织目前要求所有外部访客启用双重验证。关闭双重验证后，除非重新启用，否则您将无法访问 {orgName} 组织中的文件。",
"Your phone number is set to {phoneNumber}. Authentication codes will be texted to this number for logging in.": "您的手机号码已设置为 {phoneNumber}。登录时，验证码将通过短信发送到此号码。",
"You can only log in to {orgName} accounts on this network.": "您只能在此网络上登录 {orgName} 账户。",
"You can only log in to accounts from {orgNames} on this network.": "您只能在此网络上登录来自 {orgNames} 的账户。",
"A configuration error prevented sign-in with Figma. Please contact your Organization administrator. Error: {ERROR}": "配置错误导致无法登录 Figma。请联系组织管理员。错误：{ERROR}",
"Entity ID does not match. {ERROR}": "实体 ID 不匹配。{ERROR}",
"{TEAM_NAME} at editor limit": "{TEAM_NAME} 已达到编辑者上限",
"{TEAM_NAME} at paid seat limit": "{TEAM_NAME} 已达到付费席位上限",
"It looks like {EMAIL} hasn't been added to Figma yet. Please contact your administrator to kick off the account creation process.": "看起来 {EMAIL} 尚未添加到 Figma。请联系管理员启动账户创建流程。",
"SMS sent to {phoneNumber}. Please allow up to a minute for the SMS to arrive, then enter the authentication code below.": "短信已发送至 {phoneNumber}。请等待最多一分钟，收到短信后输入下方验证码。",
"Code was sent to number ending in {phoneNumber}": "验证码已发送至尾号为 {phoneNumber} 的号码",
"SMS sent to number ending in {phoneNumber}": "短信已发送至尾号为 {phoneNumber} 的号码",
"A code has been sent to your email {email}.": "验证码已发送到您的邮箱 {email}。",
"Click on the link we sent to {emailAddress} to finish your account setup.": "请点击我们发送至 {emailAddress} 的链接完成账户设置。",
"Couldn’t rename {count} layers": "无法重命名 {count} 个图层",
"This will update your seat in {planName}—you’ll get full access to FigJam and Figma Slides.": "这将更新您在 {planName} 中的席位—您将可以完整使用 FigJam 和 Figma Slides。",
"This will update your seat in {planName}—you’ll get full access to Figma Design, Dev Mode, FigJam, and Figma Slides.": "这将更新您在 {planName} 中的席位—您将可以完整使用 Figma Design、Dev Mode、FigJam 和 Figma Slides。",
"A Full seat in {planName} includes higher AI credit limits and full access to Figma Design, Dev Mode, FigJam, and Figma Slides.": "{planName} 中的完整席位包含更高的 AI 点数上限，并可完整使用 Figma Design、Dev Mode、FigJam 和 Figma Slides。",
"A Full seat in {planName} includes higher MCP tool call limits and full access to Figma Design, Dev Mode, FigJam, and Figma Slides.": "{planName} 中的完整席位包含更高的 MCP 工具调用上限，并可完整使用 Figma Design、Dev Mode、FigJam 和 Figma Slides。",
"You’ve been invited to edit this Figma Design file. This will update your seat in {planName}—you’ll get full access to Figma Design, Dev Mode, FigJam, and Figma Slides.": "您已受邀编辑此 Figma Design 文件。这将更新您在 {planName} 中的席位—您将可以完整使用 Figma Design、Dev Mode、FigJam 和 Figma Slides。",
"A Collab seat in {planName} includes higher AI credit limits and full access to FigJam and Figma Slides.": "{planName} 中的协作席位包含更高的 AI 点数上限，并可完整使用 FigJam 和 Figma Slides。",
"You’ve been invited to edit this FigJam file. This will update your seat in {planName}—you’ll get full access to FigJam and Figma Slides.": "您已受邀编辑此 FigJam 文件。这将更新您在 {planName} 中的席位—您将可以完整使用 FigJam 和 Figma Slides。",
"This will update your seat in {planName}—you’ll get full access to Figma Make, Figma Design, Figma Sites, Dev Mode, FigJam, and Figma Slides": "这将更新您在 {planName} 中的席位—您将可以完整使用 Figma Make、Figma Design、Figma Sites、Dev Mode、FigJam 和 Figma Slides",
"A Full seat in {planName} includes higher AI credit limits and full access to Figma Make, Figma Design, Figma Sites, Dev Mode, FigJam, and Figma Slides": "{planName} 中的完整席位包含更高的 AI 点数上限，并可完整使用 Figma Make、Figma Design、Figma Sites、Dev Mode、FigJam 和 Figma Slides",
"{upgrader_name} accepted invite to org": "{upgrader_name} 接受邀请加入组织",
"{upgrader_name} ran a plugin": "{upgrader_name} 运行了插件",
"{upgrader_name} was provisioned with a paid seat by SCIM": "{upgrader_name} 由 SCIM 配置了付费席位",
"Changed {name} to allow anyone with the link to edit": "已将 {name} 更改为允许任何拥有链接的人编辑",
"Removed link access for {name}": "已移除 {name} 的链接访问权限",
"Changed {name} to allow anyone with the link to view": "已将 {name} 更改为允许任何拥有链接的人查看",
"Changed {name} to allow anyone with a prototype link to view": "已将 {name} 更改为允许任何拥有原型链接的人查看",
"Deleted codebase import(s) for {repoIdentifiers}": "已删除 {repoIdentifiers} 的代码仓库导入",
"Enabled idle session timeout for {duration}": "已为 {duration} 启用闲置会话超时",
"Custom settings for AI features were removed for the {workspaceName} workspace and they will now be disabled according to the organization’s settings": "已移除 {workspaceName} 工作区的 AI 功能自定义设置，现将根据组织设置禁用这些功能",
"Custom settings for AI features were removed for the {workspaceName} workspace and they will now be enabled according to the organization’s settings": "已移除 {workspaceName} 工作区的 AI 功能自定义设置，现将根据组织设置启用这些功能",
"Custom settings for enabling asset approval in Buzz were removed for {workspaceName}": "已移除 {workspaceName} 的 Buzz 素材审批启用自定义设置",
"Custom settings for requiring asset approval in Buzz were removed for {workspaceName}": "已移除 {workspaceName} 的 Buzz 素材审批要求自定义设置",
"Exported the {workspaceName} workspace team list to CSV": "已将 {workspaceName} 工作区的团队列表导出为 CSV",
"Removed {userEmail} from the organization's Draft": "已将 {userEmail} 从组织的草稿中移除",
"{upgrader_name} joined with a paid seat due to the organization's default role": "{upgrader_name} 因组织的默认角色加入并获得付费席位",
"{upgrader_name} was upgraded when an owner left the team": "{upgrader_name} 在所有者离开团队后获得升级",
"{upgrader_name} was upgraded from Dev Mode beta per your org's contract": "根据组织合同，{upgrader_name} 已从 Dev Mode Beta 升级",
"Tentative access to a {seatType} seat ended because a different seat was requested.": "由于申请了其他席位，对 {seatType} 席位的临时访问权限已结束。",
"Tentative access to a {seatType} seat ended because seat request was approved.": "由于席位申请已获批准，对 {seatType} 席位的临时访问权限已结束。",
"No longer has access to a {seatType} seat because admin declined the seat request.": "由于管理员拒绝了席位申请，已不再拥有 {seatType} 席位的访问权限。",
"Granted tentative access to a {seatType} seat because of a seat request.": "由于提交了席位申请，已获得 {seatType} 席位的临时访问权限。",
"These drafts belonged to users who were removed from {teamName}": "这些草稿属于已从 {teamName} 团队移除的用户",
"Changed Make & Agent network access hostnames to {newHosts}": "已将 Make 和 Agent 网络访问主机名更改为 {newHosts}",
"Figma support enabled upgrade request rerouting for {currentAudience}": "Figma 支持已为 {currentAudience} 启用升级请求转交",
"Changed the guest invite setting to {guestSetting}": "已将访客邀请设置更改为 {guestSetting}",
"Disabled Figma Support visibility for {orgName}": "已为 {orgName} 禁用 Figma 支持可见性",
"Enabled Figma Support visibility for {orgName}": "已为 {orgName} 启用 Figma 支持可见性",
"Joined the external team {teamName}": "已加入外部团队 {teamName}",
"Left the external team {teamName}": "已离开外部团队 {teamName}",
"Created user group {userGroupName}": "已创建用户组 {userGroupName}",
"Deleted user group {userGroupName}": "已删除用户组 {userGroupName}",
"Approval setting for this seat at the time of request was {approvalSetting}.": "此席位在提出请求时的审批设置为 {approvalSetting}。",
"Disabled open sessions for the {orgName} organization": "已为 {orgName} 组织禁用开放会话",
"Enabled open sessions for the {orgName} organization": "已为 {orgName} 组织启用开放会话",
"Moved {name} to the trash": "已将 {name} 移到回收站",
"Ended an open session on {name}": "已结束在 {name} 上的开放会话",
"Started an open session on {name}": "已在 {name} 上开始开放会话",
"Disabled REST API plan access tokens for {orgName}": "已为 {orgName} 禁用 REST API 套餐访问令牌",
"Enabled REST API plan access tokens for {orgName}": "已为 {orgName} 启用 REST API 套餐访问令牌",
"Requested an upgrade to {seatType}.": "已申请升级为 {seatType}。",
"Go to source": "转到源代码",
"Stay logged in": "保持登录",
"Call number": "拨打电话",
"Create preview": "创建预览",
"Invalid link": "链接无效",
"Send mail": "发送邮件",
"Specs is confidential, click to learn more": "Specs 为保密功能，点击了解详情",
"You are currently viewing frontend code from commit": "你当前查看的前端代码来自提交",
"Copy/Paste as -> Copy as code": "复制/粘贴为 → 复制为代码",
"Must be >= 1": "必须大于或等于 1",
"Must be >= 0": "必须大于或等于 0",
"Must be > 0": "必须大于 0",
"Variable name cannot include the following symbols: '{ }' . $": "变量名称不能包含以下符号：'{ }' . $",
"Add collaborators": "添加协作者",
"Billing admin": "账单管理员",
"Org admin": "组织管理员",
"Org domain management": "组织域名管理",
"Identity Providers": "身份提供商",
"Resource unavailable": "资源不可用",
"Team Admin Console": "团队管理控制台",
"Summary stopped because the spec changed.": "由于规格说明发生变化，摘要生成已停止。",
"Circle (1:1)": "圆形（1:1）",
"Add code": "添加代码",
"Stamp count": "印章数量",
"Stamp type": "印章类型",
"Merge cells": "合并单元格",
"Split cell": "拆分单元格",
"Access file": "访问文件",
"Lock options": "锁定选项",
"Ex: en": "例如：en",
"carousel": "轮播",
"Restored the {folderName} project": "已恢复 {folderName} 项目",
"Restored the {folderName} folder": "已恢复 {folderName} 文件夹",
"Changed the org access of the {folderName} project to edit": "已将组织对 {folderName} 项目的访问权限更改为可编辑",
"Changed the org access of the {folderName} folder to edit": "已将组织对 {folderName} 文件夹的访问权限更改为可编辑",
"Removed org access for the {folderName} project": "已移除组织对 {folderName} 项目的访问权限",
"Created shader effect {shaderEffectName}": "已创建着色器效果 {shaderEffectName}",
"Deleted shader effect {shaderEffectName}": "已删除着色器效果 {shaderEffectName}",
"Updated shader effect {shaderEffectName}": "已更新着色器效果 {shaderEffectName}",
"Created shader fill {shaderFillName}": "已创建着色器填充 {shaderFillName}",
"Deleted shader fill {shaderFillName}": "已删除着色器填充 {shaderFillName}",
"Updated shader fill {shaderFillName}": "已更新着色器填充 {shaderFillName}",
"Set a password for site/app {name}": "已为网站/应用 {name} 设置密码",
"Set a password for specific pages of site/app {name}": "已为网站/应用 {name} 的指定页面设置密码",
"Unset the password for site/app {name}": "已取消网站/应用 {name} 的密码",
"Unset the password for specific pages of site/app {name}": "已取消网站/应用 {name} 指定页面的密码",
"Removed requirement for widget approval for {org}": "已取消 {org} 的小部件审批要求",
"Updated {org} to require approval for widgets": "已将 {org} 的设置更改为小部件需要审批",
"Installed widget {widgetName} for everyone": "已为所有人安装小部件 {widgetName}",
"Changed {userEmail}’s AI credit limit via SCIM": "已通过 SCIM 更改 {userEmail} 的 AI 点数上限",
"Removed {userEmail}’s access to paid AI credits": "已移除 {userEmail} 的付费 AI 点数使用权限",
"Removed paid credit access from {userEmail}": "已移除 {userEmail} 的付费点数使用权限",
"Gave {userEmail} access to paid AI credits": "已授予 {userEmail} 付费 AI 点数使用权限",
"Gave paid credit access to {userEmail}": "已授予 {userEmail} 付费点数使用权限",
"Changed default AI credit increase to {newAmount} credits": "已将默认 AI 点数增加额度更改为 {newAmount} 点",
"Removed default guest access duration of {oldDays} days": "已移除 {oldDays} 天的默认访客访问期限",
"Set default guest access duration to {days} days": "已将默认访客访问期限设为 {days} 天",
"Disabled external collaboration controls in the {orgName} organization": "已在 {orgName} 组织中禁用外部协作控制",
"Enabled external collaboration controls in the {orgName} organization": "已在 {orgName} 组织中启用外部协作控制",
"Created a new file in the {folder} project": "已在 {folder} 项目中新建文件",
"Created a new file in the {folder} folder": "已在 {folder} 文件夹中新建文件",
"Duplicated the {name} file": "已创建 {name} 文件的副本",
"Exported the contents of the {name} file": "已导出 {name} 文件的内容",
"Downloaded an image from the {name} file": "已从 {name} 文件下载图片",
"Viewed a public file in external organization {orgName}": "已查看外部组织 {orgName} 中的公开文件",
"Accepted invite as a publisher to widget {widgetName}": "已接受邀请，成为小部件 {widgetName} 的发布者",
"Uninstalled widget {widgetName} for everyone": "已为所有人卸载小部件 {widgetName}",
"Asset approval in Buzz has been changed to required for {workspaceName}": "已将 {workspaceName} 的 Buzz 素材审批改为必需",
"Asset approval in Buzz has been disabled for {workspaceName}": "已为 {workspaceName} 禁用 Buzz 素材审批",
"Asset approval in Buzz has been enabled for {workspaceName}": "已为 {workspaceName} 启用 Buzz 素材审批",
"Asset approval in Buzz has been changed to optional for {workspaceName}": "已将 {workspaceName} 的 Buzz 素材审批改为可选",
"Created a new workspace called {workspaceName}": "已创建名为 {workspaceName} 的新工作区",
"Deleted the {workspaceName} workspace": "已删除 {workspaceName} 工作区",
"Created SCIM group {name}": "已创建 SCIM 用户组 {name}",
"Deleted SCIM group {name}": "已删除 SCIM 用户组 {name}",
"Archived branch {name}": "已归档分支 {name}",
"Created branch {name}": "已创建分支 {name}",
"Deleted branch {name}": "已删除分支 {name}",
"Merged branch {name}": "已合并分支 {name}",
"Unarchived branch {name}": "已取消归档分支 {name}",
"Updated branch {name}": "已更新分支 {name}",
"Confirmed seat renewals for {orgName}.": "已确认 {orgName} 的席位续订。",
"Confirmed plan renewal for {orgName}.": "已确认 {orgName} 的套餐续订。",
"Custom domain {domain} activated": "自定义域名 {domain} 已激活",
"Custom domain {domain} removed": "自定义域名 {domain} 已移除",
"Published a site/app to {domain}": "已将网站/应用发布到 {domain}",
"Unpublished a site/app from {domain}": "已从 {domain} 取消发布网站/应用",
"Deleted the {teamName} team": "已删除 {teamName} 团队",
"Exported the {billingGroupName} billing group members list to CSV": "已将 {billingGroupName} 账单组成员列表导出为 CSV",
"Exported the {teamName} team out of the organization": "已将 {teamName} 团队导出到组织外",
"Exported the {workspaceName} workspace members list to CSV": "已将 {workspaceName} 工作区成员列表导出为 CSV",
"Imported the {teamName} team into the organization": "已将 {teamName} 团队导入组织",
"Restored the {teamName} team": "已恢复 {teamName} 团队",
"{teamName} wants to transfer their team into the organization": "{teamName} 希望将其团队转移到组织",
"Joined call on file {figFileKey}": "已加入文件 {figFileKey} 的通话",
"Disabled the {modelName} Figma Weave AI model": "已禁用 Figma Weave AI 模型 {modelName}",
"Enabled the {modelName} Figma Weave AI model": "已启用 Figma Weave AI 模型 {modelName}",
"Disabled featured connectors for {orgName}": "已为 {orgName} 禁用精选连接器",
"Enabled featured connectors for {orgName}": "已为 {orgName} 启用精选连接器",
"Disabled custom connectors for {orgName}": "已为 {orgName} 禁用自定义连接器",
"Enabled custom connectors for {orgName}": "已为 {orgName} 启用自定义连接器",
"Published npm registry package {packageName}": "已发布 npm 软件包仓库中的软件包 {packageName}",
"Unpublished npm registry package {packageName}": "已取消发布 npm 软件包仓库中的软件包 {packageName}",
"Created npm registry scopes: {scopes}": "已创建 npm 软件包仓库作用域：{scopes}",
"Deleted npm registry scopes: {scopes}": "已删除 npm 软件包仓库作用域：{scopes}",
"Disabled domain capture in the {orgName} organization": "已在 {orgName} 组织中禁用域名自动收纳",
"Enabled domain capture in the {orgName} organization": "已在 {orgName} 组织中启用域名自动收纳",
"Joined the external org {orgName}": "已加入外部组织 {orgName}",
"Left the external org {orgName}": "已离开外部组织 {orgName}",
"Created a new plan access token with scopes: {scopes}": "已创建新的套餐访问令牌，权限范围为：{scopes}",
"Refreshed the {tokenName} plan access token": "已刷新套餐访问令牌 {tokenName}",
"Removed requirement for plugin approval for {org}": "已移除 {org} 的插件审批要求",
"Updated {org} to require approval for plugins": "已将 {org} 设置为插件需要审批",
"Installed plugin {pluginName} for everyone": "已为所有人安装插件 {pluginName}",
"Accepted invite as a publisher to plugin {pluginName}": "已接受邀请，成为插件 {pluginName} 的发布者",
"Uninstalled plugin {pluginName} for everyone": "已为所有人卸载插件 {pluginName}",
"Agreed to the organization's {title} policy": "已同意组织的 {title} 政策",
"Disabled the organization's {title} policy": "已禁用组织的 {title} 政策",
"Enabled the organization's {title} policy": "已启用组织的 {title} 政策",
"Event of type {eventName} is not configured for viewing in Admin. Ask for help in #feat-support-activity-logs.": "尚未配置在管理后台查看 {eventName} 类型的事件。请在 #feat-support-activity-logs 中寻求帮助。",
"Changed the org access of the {folderName} project to view": "已将 {folderName} 项目的组织访问权限改为可查看",
"Changed the org access of the {folderName} folder to view": "已将 {folderName} 文件夹的组织访问权限改为可查看",
"Removed org access for the {folderName} folder": "已移除组织对 {folderName} 文件夹的访问权限",
"Changed the team access of the {folderName} project to edit": "已将 {folderName} 项目的团队访问权限改为可编辑",
"Changed the team access of the {folderName} folder to edit": "已将 {folderName} 文件夹的团队访问权限改为可编辑",
"Removed team access for the {folderName} project": "已移除团队对 {folderName} 项目的访问权限",
"Removed team access for the {folderName} folder": "已移除团队对 {folderName} 文件夹的访问权限",
"Changed the team access of the {folderName} project to view": "已将 {folderName} 项目的团队访问权限改为可查看",
"Changed the team access of the {folderName} folder to view": "已将 {folderName} 文件夹的团队访问权限改为可查看",
"Approved the transfer of the {folderName} project to the organization": "已批准将 {folderName} 项目转移到组织",
"Approved the transfer of the {folderName} folder to the organization": "已批准将 {folderName} 文件夹转移到组织",
"Approved the transfer of a copy of the {folderName} project to the organization": "已批准将 {folderName} 项目的副本转移到组织",
"Approved the transfer of a copy of the {folderName} folder to the organization": "已批准将 {folderName} 文件夹的副本转移到组织",
"Trashed the {folderName} project": "已将 {folderName} 项目移到回收站",
"Trashed the {folderName} folder": "已将 {folderName} 文件夹移到回收站",
"Installed Figma's GitHub app for {login}": "已为 {login} 安装 Figma 的 GitHub 应用",
"Suspended Figma's GitHub app for {login}": "已暂停 {login} 的 Figma GitHub 应用",
"Uninstalled Figma's GitHub app for {login}": "已为 {login} 卸载 Figma 的 GitHub 应用",
"Unsuspended Figma's GitHub app for {login}": "已解除对 {login} 的 Figma GitHub 应用的暂停",
"Granted Figma's GitHub app access to repository {repository}": "已授予 Figma 的 GitHub 应用访问代码仓库 {repository} 的权限",
"Disabled Figma's GitHub app access to repository {repository}": "已禁用 Figma 的 GitHub 应用对代码仓库 {repository} 的访问",
"Enabled Figma's GitHub app access to repository {repository}": "已启用 Figma 的 GitHub 应用对代码仓库 {repository} 的访问",
"Removed Figma's GitHub app access to repository {repository}": "已移除 Figma 的 GitHub 应用对代码仓库 {repository} 的访问权限",
"Added an IdP configuration with tenant ID {sp_tenant_id}": "已添加租户 ID 为 {sp_tenant_id} 的身份提供方配置",
"Removed an IdP configuration with tenant ID {sp_tenant_id}": "已移除租户 ID 为 {sp_tenant_id} 的身份提供方配置",
"Updated an IdP configuration with tenant ID {sp_tenant_id}": "已更新租户 ID 为 {sp_tenant_id} 的身份提供方配置",
"Allowlisted IP range {ip_address}": "已将 IP 范围 {ip_address} 加入允许列表",
"Removed IP range {ip_address} from the allowlist": "已将 IP 范围 {ip_address} 移出允许列表",
"Added network access restriction for IP range {ip_address} (Not yet enabled)": "已为 IP 范围 {ip_address} 添加网络访问限制（尚未启用）",
"Removed network access restriction for IP range {ip_address}": "已移除 IP 范围 {ip_address} 的网络访问限制",
"Disabled network access restriction for IP range {ip_address}": "已禁用 IP 范围 {ip_address} 的网络访问限制",
"Enabled network access restriction for IP range {ip_address}": "已启用 IP 范围 {ip_address} 的网络访问限制",
"Selected the {workspaceName} workspace": "已选择 {workspaceName} 工作区",
"Imported Storybook project {projectName}": "已导入 Storybook 项目 {projectName}",
"Deleted Storybook project {projectName}": "已删除 Storybook 项目 {projectName}",
"Updated design files for Storybook project {projectName}": "已更新 Storybook 项目 {projectName} 的设计文件",
"Deleted a storybook build from Storybook project {projectName}": "已从 Storybook 项目 {projectName} 中删除一个 Storybook 构建",
"Set an expiration for a public link to the {name} file": "已为 {name} 文件的公开链接设置到期时间",
"Updated the expiration for a public link to the {name} file": "已更新 {name} 文件公开链接的到期时间",
"Removed the expiration for a public link to the {name} file": "已移除 {name} 文件公开链接的到期时间",
"Moved the {name} file to their drafts folder": "已将 {name} 文件移到其草稿文件夹",
"Removed prototype link access for {name}": "已移除 {name} 的原型链接访问权限",
"Disabled separate prototype link access for {name}": "已禁用 {name} 的独立原型链接访问权限",
"Restored {name} from the trash": "已从回收站恢复 {name}",
"Saved {name} as a .fig file": "已将 {name} 保存为 .fig 文件",
"Set a password on prototype link access for {name}": "已为 {name} 的原型链接访问设置密码",
"Changed {name} to allow viewers to copy, share, and export the file": "已将 {name} 设置为允许查看者复制、分享和导出文件",
"Changed {name} to disallow viewers from copying, sharing, and exporting the file": "已将 {name} 设置为不允许查看者复制、分享和导出文件",
"Allowed exporting for all viewers for {orgName}": "已允许 {orgName} 的所有查看者导出",
"Restricted exporting for all viewers for {orgName}": "已限制 {orgName} 的所有查看者导出",
"Retricted exporting for guest viewers for {orgName}": "已限制 {orgName} 的访客查看者导出",
"Deleted the {folderName} project": "已删除 {folderName} 项目",
"Deleted the {folderName} folder": "已删除 {folderName} 文件夹",
"Created a duplicate folder {folderName}": "已创建文件夹副本 {folderName}",
"Exported the {folderName} project out of the organization": "已将 {folderName} 项目导出到组织外",
"Exported the {folderName} folder out of the organization": "已将 {folderName} 文件夹导出到组织外",
"Imported the {folderName} project into the organization": "已将 {folderName} 项目导入组织",
"Imported the {folderName} folder into the organization": "已将 {folderName} 文件夹导入组织",
"Disabled inherited permissions from its parent for the {folderName} folder": "已禁用 {folderName} 文件夹从父级继承权限",
"Restored inherited permissions for the {folderName} folder": "已恢复 {folderName} 文件夹的权限继承",
"Edited billing group credits from {oldCredits} to {newCredits} for {billingGroupName}": "已将 {billingGroupName} 的账单组点数从 {oldCredits} 修改为 {newCredits}",
"Removed billing group credits from {billingGroupName}": "已移除 {billingGroupName} 的账单组点数",
"Set aside {credits} billing group credits for {billingGroupName}": "已为 {billingGroupName} 预留 {credits} 账单组点数",
"Created a new billing group called {billingGroupName}": "已创建名为 {billingGroupName} 的新账单组",
"Deleted the {billingGroupName} billing group": "已删除 {billingGroupName} 账单组",
"Selected the {billingGroupName} billing group": "已选择 {billingGroupName} 账单组",
"Deleted CMS resource {name}": "已删除 CMS 资源 {name}",
"Permanently deleted CMS resource {name}": "已永久删除 CMS 资源 {name}",
"Deleted file {fileName} from Community": "已从社区删除文件 {fileName}",
"Published file {fileName} to Community": "已将文件 {fileName} 发布到社区",
"Updated file {fileName} in Community": "已更新社区中的文件 {fileName}",
"Deleted plugin {pluginName} from Community": "已从社区删除插件 {pluginName}",
"Published plugin {pluginName} to Community": "已将插件 {pluginName} 发布到社区",
"Deleted widget {widgetName} from Community": "已从社区删除小部件 {widgetName}",
"Published widget {widgetName} to Community": "已将小部件 {widgetName} 发布到社区",
"Updated plugin {pluginName} to Community": "已更新社区中的插件 {pluginName}",
"Updated widget {widgetName} to Community": "已更新社区中的小部件 {widgetName}",
  "Disabled community resources in template picker for {orgName} (Buzz only)": "已为 {orgName} 禁用模板选择器中的社区资源（仅限 Buzz）",
  "Enabled community resources in template picker for {orgName} (Buzz only)": "已为 {orgName} 启用模板选择器中的社区资源（仅限 Buzz）",
  "Unsplash in Buzz setting was disabled for {orgName}": "已为 {orgName} 禁用 Buzz 中的 Unsplash 设置",
  "Unsplash in Buzz setting was enabled for {orgName}": "已为 {orgName} 启用 Buzz 中的 Unsplash 设置",
  "Disabled cursor chat for the {orgName} organization": "已为 {orgName} 组织禁用光标聊天",
  "Enabled cursor chat for the {orgName} organization": "已为 {orgName} 组织启用光标聊天",
  "Disabled public links for the {orgName} organization": "已为 {orgName} 组织禁用公开链接",
  "Enabled public links for the {orgName} organization": "已为 {orgName} 组织启用公开链接",
  "Disabled public links for the {workspaceName} workspace": "已为 {workspaceName} 工作区禁用公开链接",
  "Enabled public links for the {workspaceName} workspace": "已为 {workspaceName} 工作区启用公开链接",
  "Allowed public links with passwords for the {orgName} organization": "已允许 {orgName} 组织使用带密码的公开链接",
  "Allowed public links with passwords for the {workspaceName} workspace": "已允许 {workspaceName} 工作区使用带密码的公开链接",
  "Disabled web publishing for {orgName}": "已为 {orgName} 禁用网页发布",
  "Enabled web publishing for {orgName}": "已为 {orgName} 启用网页发布",
  "Disabled Supabase integration for {orgName}": "已为 {orgName} 禁用 Supabase 集成",
  "Enabled Supabase integration for {orgName}": "已为 {orgName} 启用 Supabase 集成",
  "Connected Supabase project to the {name} file": "已将 Supabase 项目连接到 {name} 文件",
  "Disconnected Supabase project from the {name} file": "已断开 Supabase 项目与 {name} 文件的连接",
  "Created generative plugin {pluginName}": "已创建生成式插件 {pluginName}",
  "Deleted generative plugin {pluginName}": "已删除生成式插件 {pluginName}",
  "Updated generative plugin {pluginName}": "已更新生成式插件 {pluginName}"
};

test("组织设置与集成活动日志模板在展开后正确匹配", () => {
  const context = vm.createContext({ document: { readyState: "loading", addEventListener() {}, querySelectorAll: () => [] }, Node: { ELEMENT_NODE: 1 } });
  vm.runInContext(runtime.replace("const map={};", "const map="+JSON.stringify({...dictionary, ...menuDictionary})+";").replace("function start(){", "globalThis.lookupForTest=lookup;\nfunction start(){"), context);
  const input = { nodeType: 1, tagName: "INPUT", parentElement: null, matches: selector => selector === 'input,textarea,[contenteditable="true"],[role="textbox"]', closest: () => null, getAttribute: () => null };
  for (const [source, target] of Object.entries(fixtures)) {
    assert.equal(dictionary[source], target.endsWith(" ") ? target.trimEnd() : target);
    for (const value of ["研发 & Design", "Alpha (Beta)", "插件 $& [v2]"]) {
      const expand = text => text.replace(/\{(\w+)\}/g, (_, key) => key === 'oldCredits' ? '1,000' : key === 'newCredits' ? '2,000' : key === 'credits' ? '500' : value);
      const renderedSource = expand(source);
      const renderedTarget = expand(target);
      assert.equal(context.lookupForTest(renderedSource), renderedTarget, renderedSource);
      assert.equal(context.lookupForTest(renderedSource, input), undefined);
    }
  }
  assert.equal(context.lookupForTest("Created generative plugin"), undefined);
  assert.equal(context.lookupForTest("Disabled web publishing"), undefined);
  assert.equal(context.lookupForTest("Edited a completely unrelated sentence"), undefined);
  assert.equal(context.lookupForTest("Edited billing group credits from unlimited to none for Example"), undefined);
  assert.equal(context.lookupForTest("Edited 2 days ago"), "编辑于 2 天前");
  assert.equal(context.lookupForTest("Deleted the  folder"), undefined);
  assert.equal(context.lookupForTest("Set an expiration for a public link to the  file"), undefined);
  assert.equal(context.lookupForTest("Edited September 9, 2026"), "编辑于 2026年9月9日");
});
